language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"

  deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-west-2"
  app: "node-docker"
  env: "Nodedocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-719156614080"
  on:
    branch: master