language: node_js

node_js: node

sudo: required

services:
  - docker

script: 
  - docker build -t tikal-devops/sample


after_deploy:
  - echo "done deploying"

  deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: "$SECRETACCESSKEY"
  region: "us-west-2"
  app: "node-docker"
  env: "Nodedocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-719156614080"
  on:
    branch: main
  skip_cleanup: true